// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWISktt3XqUns0_DmhyaZebkFfbg72t7c',
    appId: '1:744529251101:web:9151c6916426e6fd66aff4',
    messagingSenderId: '744529251101',
    projectId: 'appprueba-16698',
    authDomain: 'appprueba-16698.firebaseapp.com',
    databaseURL: 'https://appprueba-16698-default-rtdb.firebaseio.com',
    storageBucket: 'appprueba-16698.appspot.com',
    measurementId: 'G-MZ94LY5SEL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIcqKTc9ZaJ2XkIhqha6UfHow35GIDkRI',
    appId: '1:744529251101:android:417af90ef20c67fd66aff4',
    messagingSenderId: '744529251101',
    projectId: 'appprueba-16698',
    databaseURL: 'https://appprueba-16698-default-rtdb.firebaseio.com',
    storageBucket: 'appprueba-16698.appspot.com',
  );
}
